namespace Moka.Beer.Common.Enums;

public enum Color
{
    [CssClass("")] Default,
    [CssClass("fill")] Fill,
    [CssClass("primary")] Primary,
    [CssClass("secondary")] Secondary,
    [CssClass("tertiary")] Tertiary,
    [CssClass("primary-container")] PrimaryContainer,
    [CssClass("secondary-container")] SecondaryContainer,
    [CssClass("tertiary-container")] TertiaryContainer,
    [CssClass("orange")] Orange,

    // Amber variants
    [CssClass("amber1")] Amber1,
    [CssClass("amber2")] Amber2,
    [CssClass("amber3")] Amber3,
    [CssClass("amber4")] Amber4,
    [CssClass("amber5")] Amber5,
    [CssClass("amber6")] Amber6,
    [CssClass("amber7")] Amber7,
    [CssClass("amber8")] Amber8,
    [CssClass("amber9")] Amber9,
    [CssClass("amber10")] Amber10,
    [CssClass("amber")] Amber,
    [CssClass("amber-border")] AmberBorder,
    [CssClass("amber-text")] AmberText,

    // Blue variants
    [CssClass("blue1")] Blue1,
    [CssClass("blue2")] Blue2,
    [CssClass("blue3")] Blue3,
    [CssClass("blue4")] Blue4,
    [CssClass("blue5")] Blue5,
    [CssClass("blue6")] Blue6,
    [CssClass("blue7")] Blue7,
    [CssClass("blue8")] Blue8,
    [CssClass("blue9")] Blue9,
    [CssClass("blue10")] Blue10,
    [CssClass("blue")] Blue,
    [CssClass("blue-border")] BlueBorder,
    [CssClass("blue-text")] BlueText,

    // Blue-grey variants
    [CssClass("blue-grey1")] BlueGrey1,
    [CssClass("blue-grey2")] BlueGrey2,
    [CssClass("blue-grey3")] BlueGrey3,
    [CssClass("blue-grey4")] BlueGrey4,
    [CssClass("blue-grey5")] BlueGrey5,
    [CssClass("blue-grey6")] BlueGrey6,
    [CssClass("blue-grey7")] BlueGrey7,
    [CssClass("blue-grey8")] BlueGrey8,
    [CssClass("blue-grey9")] BlueGrey9,
    [CssClass("blue-grey10")] BlueGrey10,
    [CssClass("blue-grey")] BlueGrey,
    [CssClass("blue-grey-border")] BlueGreyBorder,
    [CssClass("blue-grey-text")] BlueGreyText,

    // Brown variants
    [CssClass("brown1")] Brown1,
    [CssClass("brown2")] Brown2,
    [CssClass("brown3")] Brown3,
    [CssClass("brown4")] Brown4,
    [CssClass("brown5")] Brown5,
    [CssClass("brown6")] Brown6,
    [CssClass("brown7")] Brown7,
    [CssClass("brown8")] Brown8,
    [CssClass("brown9")] Brown9,
    [CssClass("brown10")] Brown10,
    [CssClass("brown")] Brown,
    [CssClass("brown-border")] BrownBorder,
    [CssClass("brown-text")] BrownText,

    // Cyan variants
    [CssClass("cyan1")] Cyan1,
    [CssClass("cyan2")] Cyan2,
    [CssClass("cyan3")] Cyan3,
    [CssClass("cyan4")] Cyan4,
    [CssClass("cyan5")] Cyan5,
    [CssClass("cyan6")] Cyan6,
    [CssClass("cyan7")] Cyan7,
    [CssClass("cyan8")] Cyan8,
    [CssClass("cyan9")] Cyan9,
    [CssClass("cyan10")] Cyan10,
    [CssClass("cyan")] Cyan,
    [CssClass("cyan-border")] CyanBorder,
    [CssClass("cyan-text")] CyanText,

    // Deep-orange variants
    [CssClass("deep-orange1")] DeepOrange1,
    [CssClass("deep-orange2")] DeepOrange2,
    [CssClass("deep-orange3")] DeepOrange3,
    [CssClass("deep-orange4")] DeepOrange4,
    [CssClass("deep-orange5")] DeepOrange5,
    [CssClass("deep-orange6")] DeepOrange6,
    [CssClass("deep-orange7")] DeepOrange7,
    [CssClass("deep-orange8")] DeepOrange8,
    [CssClass("deep-orange9")] DeepOrange9,
    [CssClass("deep-orange10")] DeepOrange10,
    [CssClass("deep-orange")] DeepOrange,
    [CssClass("deep-orange-border")] DeepOrangeBorder,
    [CssClass("deep-orange-text")] DeepOrangeText,

    // Deep-purple variants
    [CssClass("deep-purple1")] DeepPurple1,
    [CssClass("deep-purple2")] DeepPurple2,
    [CssClass("deep-purple3")] DeepPurple3,
    [CssClass("deep-purple4")] DeepPurple4,
    [CssClass("deep-purple5")] DeepPurple5,
    [CssClass("deep-purple6")] DeepPurple6,
    [CssClass("deep-purple7")] DeepPurple7,
    [CssClass("deep-purple8")] DeepPurple8,
    [CssClass("deep-purple9")] DeepPurple9,
    [CssClass("deep-purple10")] DeepPurple10,
    [CssClass("deep-purple")] DeepPurple,
    [CssClass("deep-purple-border")] DeepPurpleBorder,
    [CssClass("deep-purple-text")] DeepPurpleText,

    // Green variants
    [CssClass("green1")] Green1,
    [CssClass("green2")] Green2,
    [CssClass("green3")] Green3,
    [CssClass("green4")] Green4,
    [CssClass("green5")] Green5,
    [CssClass("green6")] Green6,
    [CssClass("green7")] Green7,
    [CssClass("green8")] Green8,
    [CssClass("green9")] Green9,
    [CssClass("green10")] Green10,
    [CssClass("green")] Green,
    [CssClass("green-border")] GreenBorder,
    [CssClass("green-text")] GreenText,

    // Grey variants
    [CssClass("grey1")] Grey1,
    [CssClass("grey2")] Grey2,
    [CssClass("grey3")] Grey3,
    [CssClass("grey4")] Grey4,
    [CssClass("grey5")] Grey5,
    [CssClass("grey6")] Grey6,
    [CssClass("grey7")] Grey7,
    [CssClass("grey8")] Grey8,
    [CssClass("grey9")] Grey9,
    [CssClass("grey10")] Grey10,
    [CssClass("grey")] Grey,
    [CssClass("grey-border")] GreyBorder,
    [CssClass("grey-text")] GreyText,

    // Indigo variants
    [CssClass("indigo1")] Indigo1,
    [CssClass("indigo2")] Indigo2,
    [CssClass("indigo3")] Indigo3,
    [CssClass("indigo4")] Indigo4,
    [CssClass("indigo5")] Indigo5,
    [CssClass("indigo6")] Indigo6,
    [CssClass("indigo7")] Indigo7,
    [CssClass("indigo8")] Indigo8,
    [CssClass("indigo9")] Indigo9,
    [CssClass("indigo10")] Indigo10,
    [CssClass("indigo")] Indigo,
    [CssClass("indigo-border")] IndigoBorder,
    [CssClass("indigo-text")] IndigoText,

    // Light-blue variants
    [CssClass("light-blue1")] LightBlue1,
    [CssClass("light-blue2")] LightBlue2,
    [CssClass("light-blue3")] LightBlue3,
    [CssClass("light-blue4")] LightBlue4,
    [CssClass("light-blue5")] LightBlue5,
    [CssClass("light-blue6")] LightBlue6,
    [CssClass("light-blue7")] LightBlue7,
    [CssClass("light-blue8")] LightBlue8,
    [CssClass("light-blue9")] LightBlue9,
    [CssClass("light-blue10")] LightBlue10,
    [CssClass("light-blue")] LightBlue,
    [CssClass("light-blue-border")] LightBlueBorder,
    [CssClass("light-blue-text")] LightBlueText,

    // Light-green variants
    [CssClass("light-green1")] LightGreen1,
    [CssClass("light-green2")] LightGreen2,
    [CssClass("light-green3")] LightGreen3,
    [CssClass("light-green4")] LightGreen4,
    [CssClass("light-green5")] LightGreen5,
    [CssClass("light-green6")] LightGreen6,
    [CssClass("light-green7")] LightGreen7,
    [CssClass("light-green8")] LightGreen8,
    [CssClass("light-green9")] LightGreen9,
    [CssClass("light-green10")] LightGreen10,
    [CssClass("light-green")] LightGreen,
    [CssClass("light-green-border")] LightGreenBorder,
    [CssClass("light-green-text")] LightGreenText,

    // Lime variants
    [CssClass("lime1")] Lime1,
    [CssClass("lime2")] Lime2,
    [CssClass("lime3")] Lime3,
    [CssClass("lime4")] Lime4,
    [CssClass("lime5")] Lime5,
    [CssClass("lime6")] Lime6,
    [CssClass("lime7")] Lime7,
    [CssClass("lime8")] Lime8,
    [CssClass("lime9")] Lime9,
    [CssClass("lime10")] Lime10,
    [CssClass("lime")] Lime,
    [CssClass("lime-border")] LimeBorder,
    [CssClass("lime-text")] LimeText,

    // Pink variants
    [CssClass("pink1")] Pink1,
    [CssClass("pink2")] Pink2,
    [CssClass("pink3")] Pink3,
    [CssClass("pink4")] Pink4,
    [CssClass("pink5")] Pink5,
    [CssClass("pink6")] Pink6,
    [CssClass("pink7")] Pink7,
    [CssClass("pink8")] Pink8,
    [CssClass("pink9")] Pink9,
    [CssClass("pink10")] Pink10,
    [CssClass("pink")] Pink,
    [CssClass("pink-border")] PinkBorder,
    [CssClass("pink-text")] PinkText,

    // Purple variants
    [CssClass("purple1")] Purple1,
    [CssClass("purple2")] Purple2,
    [CssClass("purple3")] Purple3,
    [CssClass("purple4")] Purple4,
    [CssClass("purple5")] Purple5,
    [CssClass("purple6")] Purple6,
    [CssClass("purple7")] Purple7,
    [CssClass("purple8")] Purple8,
    [CssClass("purple9")] Purple9,
    [CssClass("purple10")] Purple10,
    [CssClass("purple")] Purple,
    [CssClass("purple-border")] PurpleBorder,
    [CssClass("purple-text")] PurpleText,

    // Red variants
    [CssClass("red1")] Red1,
    [CssClass("red2")] Red2,
    [CssClass("red3")] Red3,
    [CssClass("red4")] Red4,
    [CssClass("red5")] Red5,
    [CssClass("red6")] Red6,
    [CssClass("red7")] Red7,
    [CssClass("red8")] Red8,
    [CssClass("red9")] Red9,
    [CssClass("red10")] Red10,
    [CssClass("red")] Red,
    [CssClass("red-border")] RedBorder,
    [CssClass("red-text")] RedText,

    // Teal variants
    [CssClass("teal1")] Teal1,
    [CssClass("teal2")] Teal2,
    [CssClass("teal3")] Teal3,
    [CssClass("teal4")] Teal4,
    [CssClass("teal5")] Teal5,
    [CssClass("teal6")] Teal6,
    [CssClass("teal7")] Teal7,
    [CssClass("teal8")] Teal8,
    [CssClass("teal9")] Teal9,
    [CssClass("teal10")] Teal10,
    [CssClass("teal")] Teal,
    [CssClass("teal-border")] TealBorder,
    [CssClass("teal-text")] TealText,

    // Yellow variants
    [CssClass("yellow1")] Yellow1,
    [CssClass("yellow2")] Yellow2,
    [CssClass("yellow3")] Yellow3,
    [CssClass("yellow4")] Yellow4,
    [CssClass("yellow5")] Yellow5,
    [CssClass("yellow6")] Yellow6,
    [CssClass("yellow7")] Yellow7,
    [CssClass("yellow8")] Yellow8,
    [CssClass("yellow9")] Yellow9,
    [CssClass("yellow10")] Yellow10,
    [CssClass("yellow")] Yellow,
    [CssClass("yellow-border")] YellowBorder,
    [CssClass("yellow-text")] YellowText
}