namespace Moka.Beer.Common.Enums;

public enum GridSize
{
    [CssClass("s1")] S1,
    [CssClass("s2")] S2,
    [CssClass("s3")] S3,
    [CssClass("s4")] S4,
    [CssClass("s5")] S5,
    [CssClass("s6")] S6,
    [CssClass("s7")] S7,
    [CssClass("s8")] S8,
    [CssClass("s9")] S9,
    [CssClass("s10")] S10,
    [CssClass("s11")] S11,
    [CssClass("s12")] S12,
    [CssClass("m1")] M1,
    [CssClass("m2")] M2,
    [CssClass("m3")] M3,
    [CssClass("m4")] M4,
    [CssClass("m5")] M5,
    [CssClass("m6")] M6,
    [CssClass("m7")] M7,
    [CssClass("m8")] M8,
    [CssClass("m9")] M9,
    [CssClass("m10")] M10,
    [CssClass("m11")] M11,
    [CssClass("m12")] M12,
    [CssClass("l1")] L1,
    [CssClass("l2")] L2,
    [CssClass("l3")] L3,
    [CssClass("l4")] L4,
    [CssClass("l5")] L5,
    [CssClass("l6")] L6,
    [CssClass("l7")] L7,
    [CssClass("l8")] L8,
    [CssClass("l9")] L9,
    [CssClass("l10")] L10,
    [CssClass("l11")] L11,
    [CssClass("l12")] L12
}