namespace Moka.Beer.Common.Enums;

public enum Theme
{
    [CssClass("default")] Default,
    [CssClass("light")] Light,
    [CssClass("dark")] Dark,
    [CssClass("primary")] Primary,
    [CssClass("primary-text")] PrimaryText,
    [CssClass("primary-border")] PrimaryBorder,
    [CssClass("primary-container")] PrimaryContainer,
    [CssClass("secondary")] Secondary,
    [CssClass("secondary-text")] SecondaryText,
    [CssClass("secondary-border")] SecondaryBorder,
    [CssClass("secondary-container")] SecondaryContainer,
    [CssClass("tertiary")] Tertiary,
    [CssClass("tertiary-text")] TertiaryText,
    [CssClass("tertiary-border")] TertiaryBorder,
    [CssClass("tertiary-container")] TertiaryContainer,
    [CssClass("error")] Error,
    [CssClass("error-text")] ErrorText,
    [CssClass("error-border")] ErrorBorder,
    [CssClass("error-container")] ErrorContainer,
    [CssClass("background")] Background,
    [CssClass("surface")] Surface,
    [CssClass("surface-variant")] SurfaceVariant,
    [CssClass("inverse-surface")] InverseSurface,
    [CssClass("inverse-primary")] InversePrimary,
    [CssClass("inverse-primary-text")] InversePrimaryText,
    [CssClass("inverse-primary-border")] InversePrimaryBorder,
    [CssClass("black")] Black,
    [CssClass("black-text")] BlackText,
    [CssClass("black-border")] BlackBorder,
    [CssClass("white")] White,
    [CssClass("white-text")] WhiteText,
    [CssClass("white-border")] WhiteBorder,
    [CssClass("transparent")] Transparent,
    [CssClass("transparent-text")] TransparentText,
    [CssClass("transparent-border")] TransparentBorder
}